- hosts: all
  tasks:
  - name: copy Dockerfile into Remote machine
    copy:
      src: Dockerfile
      dest: .
  - name: copy Docke-compose into Remote machine
    copy:
      src: docker-compose.yml
      dest: .
      
  - name: Stop the running container
    command: docker stop ec2-user_webapp_1
    ignore_errors: true
    
  - name: remove the running container
    command: docker rm ec2-user_webapp_1
    ignore_errors: true
    
  - name: Create and start the container using docker-compose
    command: docker-compose up -d
