- hosts: all
  tasks:
      
  - name: Stop the running container
    command: docker stop layout-dash_dashboard_1
    ignore_errors: true

  - name: remove the running container
    command: docker rm layout-dash_dashboard_1
    ignore_errors: true
    
  - name: Create and start the container using docker-compose
    command: docker-compose up -d
